version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: payslip_postgres
    ports:
      - "5100:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_portal
    volumes:
      - pgdata_payslip:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: payslip_backend
    ports:
      - "3100:3100"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: employee_portal
      DB_HOST: postgres
      DB_PORT: 5432
      PORT: 3100
    restart: always

  employee-payslip:
    build: ./Employee_Payslip
    container_name: employee_payslip_ui
    ports:
      - "8168:80"
    depends_on:
      - backend

  hr-payslip:
    build: ./HR_Payslip
    container_name: hr_payslip_ui
    ports:
      - "8169:80"
    depends_on:
      - backend

volumes:
  pgdata_payslip:

